//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Kategoriler
{
    public Kategoriler()
    {
        this.Yemekler = new HashSet<Yemekler>();
    }

    public int KategoriID { get; set; }
    public string KategoriAd { get; set; }
    public bool Silindi { get; set; }

    public virtual ICollection<Yemekler> Yemekler { get; set; }
}

public partial class Kullanicilar
{
    public Kullanicilar()
    {
        this.YemekBegeni = new HashSet<YemekBegeni>();
        this.YemekFavori = new HashSet<YemekFavori>();
        this.Yorumlar = new HashSet<Yorumlar>();
    }

    public int KullaniciID { get; set; }
    public string AdSoyad { get; set; }
    public string KullaniciAdi { get; set; }
    public string Sifre { get; set; }
    public string Yetki { get; set; }
    public string Telefon { get; set; }
    public string Adres { get; set; }
    public string Cinsiyet { get; set; }
    public string ProfilFoto { get; set; }
    public Nullable<int> GonderdigiTarifSayisi { get; set; }
    public Nullable<int> Puan { get; set; }
    public Nullable<int> YorumSayisi { get; set; }
    public Nullable<bool> Silindi { get; set; }

    public virtual ICollection<YemekBegeni> YemekBegeni { get; set; }
    public virtual ICollection<YemekFavori> YemekFavori { get; set; }
    public virtual ICollection<Yorumlar> Yorumlar { get; set; }
}

public partial class YemekBegeni
{
    public int BegeniID { get; set; }
    public int YemekID { get; set; }
    public int KullaniciID { get; set; }

    public virtual Kullanicilar Kullanicilar { get; set; }
    public virtual Yemekler Yemekler { get; set; }
}

public partial class YemekFavori
{
    public int FavoriID { get; set; }
    public Nullable<int> YemekID { get; set; }
    public Nullable<int> KullaniciID { get; set; }

    public virtual Kullanicilar Kullanicilar { get; set; }
    public virtual Yemekler Yemekler { get; set; }
}

public partial class Yemekler
{
    public Yemekler()
    {
        this.YemekBegeni = new HashSet<YemekBegeni>();
        this.YemekFavori = new HashSet<YemekFavori>();
        this.Yorumlar = new HashSet<Yorumlar>();
    }

    public int YemekID { get; set; }
    public string YemekAdi { get; set; }
    public string Malzeme { get; set; }
    public string Yapilis { get; set; }
    public string YemekFoto { get; set; }
    public int KategoriID { get; set; }
    public System.DateTime Tarih { get; set; }
    public string Gonderen { get; set; }
    public Nullable<int> YemekPuanSayisi { get; set; }
    public Nullable<int> YemekYorumSayisi { get; set; }
    public bool Onay { get; set; }
    public bool Silindi { get; set; }

    public virtual Kategoriler Kategoriler { get; set; }
    public virtual ICollection<YemekBegeni> YemekBegeni { get; set; }
    public virtual ICollection<YemekFavori> YemekFavori { get; set; }
    public virtual ICollection<Yorumlar> Yorumlar { get; set; }
}

public partial class Yorumlar
{
    public int YorumID { get; set; }
    public int YemekID { get; set; }
    public int KullaniciID { get; set; }
    public string YorumMetni { get; set; }
    public System.DateTime YorumTarihi { get; set; }
    public bool Silindi { get; set; }

    public virtual Kullanicilar Kullanicilar { get; set; }
    public virtual Yemekler Yemekler { get; set; }
}
