//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class YemekTarifEntities : DbContext
{
    public YemekTarifEntities()
        : base("name=YemekTarifEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Kategoriler> Kategoriler { get; set; }
    public DbSet<Kullanicilar> Kullanicilar { get; set; }
    public DbSet<YemekBegeni> YemekBegeni { get; set; }
    public DbSet<YemekFavori> YemekFavori { get; set; }
    public DbSet<Yemekler> Yemekler { get; set; }
    public DbSet<Yorumlar> Yorumlar { get; set; }
}
